name: gh-action-boolean-input-repro

on:
  push:
    branches:
      - master

jobs:
  testing:
    name: Bug repro
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      # Repro w/ default value
      - uses: ./
        continue-on-error: true
      # Repro w/ explicit value
      - uses: ./
        continue-on-error: true
        with:
          boolean-param: false
      # Repro w/ tagged value
      - uses: ./
        continue-on-error: true
        with:
          boolean-param: !!bool false
